### ISSUE TITLE
where is the libsonivox.so file?

### ISSUE THREAD

**Issue by rzil** [billthefarmer/accordion#2]
The readme says
Get a copy of the libsonivox.so library from an Android device or an emulator (in system/lib) and put it with the other libraries in the platforms/android-14/arch-arm/usr/lib folder of the NDK.

I have Android Studio on OS X Yosemite. I am trying to build for the emulator. Where is this system/lib directory exactly?

**Comment by billthefarmer** [comment]
In the device or emulator. The command:
adb pull system/lib/libsonivox.so .
will extract it to the current folder. I don't know anything about Android Studio, I don't use it. I also don't know if it includes the SDK and if so where it is on a Mac. See this page: https://developer.android.com/tools/help/adb.html.
On 6 Mar 2015 10:14, Ruben Zilibowitz <notifications@github.com> wrote:The readme says
Get a copy of the libsonivox.so library from an Android device or an emulator (in system/lib) and put it with the other libraries in the platforms/android-14/arch-arm/usr/lib folder of the NDK.

I have Android Studio on OS X Yosemite. I am trying to build for the emulator. Where is this system/lib directory exactly?

**Comment by rzil** [comment]
Ok I got it! Here is the path to adb on Mac

~/Library/Android/sdk/platform-tools/adb

I had to launch the emulator first and then it extracted the libsonivox.so file. Now I have copied it to platforms/android-14/arch-x86/usr/lib

Unfortunately it still does not build. Here is the first error

/Users/rzilibowitz/Documents/projects/accordion/app/src/main/jni/midi.cpp
  Error:(49) undefined reference to `EAS_Config’

**Comment by rzil** [comment]
Ok I changed the Android.mk file as follows and got it to build finally.

# for EAS midi
#LOCAL_LDLIBS    += -lsonivox
LOCAL_SHARED_LIBRARIES := sonivox
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true


However, when I run it on the emulator it just says "Unfortunately, Accordion has stopped."

**Comment by billthefarmer** [comment]
You can get the exact error from the device log with adb logcat. Because you will get pages of log info, either wait till it stops or use grep to filter out what you're looking for. I suspect you got a duff build because you ignored undefined symbols.
There are two ways you can fix it. Either look in the NDK docs to see how to add a prebuilt shared library or put the Android.mk file back the way it was and make sure you put the libsonivox.so file in the folder the NDK is looking in. You will be using a later version than what I built it with. Use ndk-build V=1 to check the library search paths.
If you use a prebuilt shared library it will be included in the apk. I don't know whether the one in the apk or the one in the device will get used. If you've only got one libsonivox.so file you need to change Application.mk to only build the ABI you want.
You will also get warning messages from the NDK about including -lsonivox, just ignore them. I can't be more specific because I am at my daughter's place in Australia, I don't have my development system.
On 6 Mar 2015 11:31, Ruben Zilibowitz <notifications@github.com> wrote:Ok I changed the Android.mk file as follows and got it to build finally.

for EAS midi

#LOCAL_LDLIBS    += -lsonivox
LOCAL_SHARED_LIBRARIES := sonivox
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true

However, when I run it on the emulator it just says "Unfortunately, Accordion has stopped."
